CLEANUP: ssl_write(): Remove a branch that cannot arise.
Importantly, encountering EOF when writing must raise an exception.
This was wrong since 2011 (3083b0e4ba1bc0cff87255b7f0994219b25b85c1),
and partially corrected in 83e55ac5c017e928d667316c334e70df6b310726.
It is fully correct since 354dd3cdb7442c992fd2aa02ed743ae82f71e6a7.

Exceptions when writing to a closed stream should look like this:

    ERROR: format/3: I/O error in write on stream <stream>(0x1d57ad0) (SSL: unexpected end-of-file)

Due to buffering, it may take several writes to reach this error.