PORT: Handle EOF portably, making copy_stream_data/2 etc. work in OpenSSL 1.1.0c.
This is necessary due to a change in behaviour of OpenSSL 1.1.0c: When
encountering EOF, SSL_read() now returns -1 instead of 0 (as it did
previously).

Note that this behaviour may change again in future versions, since it
is currently subject to debate:

   https://github.com/openssl/openssl/issues/1903

However, 1.1.0c is already published and must be accommodated, and
further, this change will remain valid even if the return value of
SSL_read() changes again, since we now explicitly check for EOF.

Test case:

    ?- http_open('https://www.metalevel.at', In, []),
       copy_stream_data(In, current_output).

Without this commit, we get with OpenSSL 1.1.0c:

    ERROR: copy_stream_data/2: I/O error in read on stream (0x2718700) (Success)