PORT: EOF when writing is now correctly handled also in OpenSSL 1.1.0c.
This has become necessary because in OpenSSL 1.1.0c, SSL_write()
returns -1 on EOF whereas it previously returned 0.

In later OpenSSL versions, the previous behaviour is restored, see:

    https://github.com/openssl/openssl/issues/1903

This commit makes the code work in 1.1.0c as well as earlier and
later versions.

Example (client.pl, server.pl closed connection) with 1.1.0c, previously:

    ...
    Client accepts the server certificate
    ERROR: Prolog initialisation failed:
    ERROR: read_util:read_line_to_codes/2: I/O error in read on stream <stream>(0x2013098) (Success)

Now:

    ...
    Client accepts the server certificate
    Foreign predicate system:close/1 did not clear exception: error(io_error(write,<stream>(0x828b08)),context(system:close/1,Broken pipe))