PORT: library(ssl) now also compiles with OpenSSL version 1.1.0, which       is needed for ChaCha20-Poly1305 and other recent ciphers.
Status:

  *) library(ssl) compiles and works for most use cases with OpenSSL 1.1.0.
  *) 47 tests pass.
  *) 2 tests fail. In both cases, certificate verification fails
     as expected, but for a different reason than expected.

Conditional compilation is used to retain backwards compatibility.
Therefore, this is ready for merging any time, to give users a chance
to compile with OpenSSL 1.1.0, run most applications, and help with testing.

One phenomenon I noticed:

    ?- http_open('https://www.metalevel.at', Stream, []),
       copy_stream_data(Stream, current_output).

This query outputs the HTML page (as expected), and then ends with:

    ERROR: copy_stream_data/2: I/O error in read on stream <stream>(0x22854d0) (Success)